# Generated by Django 5.0.4 on 2026-05-05 11:42

import apps.events.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
                ('curriculum_slug', models.CharField(blank=True, max_length=50)),
                ('source', models.CharField(choices=[('internal', '자체'), ('external', '외부')], max_length=10)),
                ('type', models.CharField(choices=[('oneday_class', '원데이 클래스'), ('study', '스터디'), ('hackathon', '해커톤'), ('seminar', '세미나'), ('mogakco', '모각코')], max_length=20)),
                ('status', models.CharField(choices=[('draft', '임시저장'), ('published', '공개'), ('cancelled', '취소')], default='draft', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('thumbnail', models.CharField(blank=True, max_length=500)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('region', models.CharField(blank=True, max_length=20)),
                ('level', models.CharField(blank=True, max_length=20)),
                ('price', models.PositiveIntegerField(default=0)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('remaining', models.PositiveIntegerField(blank=True, null=True)),
                ('min_heads', models.PositiveIntegerField(blank=True, null=True)),
                ('host_name', models.CharField(blank=True, max_length=100)),
                ('host_handle', models.CharField(blank=True, max_length=50)),
                ('external_source', models.CharField(blank=True, max_length=50)),
                ('external_url', models.URLField(blank=True)),
                ('venue', models.JSONField(blank=True, default=dict)),
                ('payment', models.JSONField(blank=True, default=dict)),
                ('policies', models.JSONField(blank=True, default=dict)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('apply_url', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'event',
                'ordering': ['start_at'],
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('token', models.SlugField(default=apps.events.models._generate_token, max_length=20, unique=True)),
                ('author_name', models.CharField(max_length=50)),
                ('author_phone', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('pending', '입금 대기'), ('confirmed', '확정'), ('cancelled', '취소'), ('attended', '출석'), ('no_show', '노쇼')], default='pending', max_length=10)),
                ('source', models.CharField(choices=[('homepage', '사이트 직접'), ('threads', 'Threads'), ('instagram', 'Instagram'), ('soomoim', '소모임'), ('other', '기타')], default='homepage', max_length=10)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('payment_method', models.CharField(default='account', max_length=20)),
                ('depositor_name', models.CharField(blank=True, max_length=50)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('attended_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('refund_amount', models.PositiveIntegerField(default=0)),
                ('memo', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'event_registration',
            },
        ),
        migrations.CreateModel(
            name='EventTestimonial',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('author_name', models.CharField(max_length=50)),
                ('author_role', models.CharField(blank=True, max_length=50)),
                ('content', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='events.event')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'event_testimonial',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['curriculum_slug'], name='event_curricu_4e495c_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['status', 'start_at'], name='event_status_9a5667_idx'),
        ),
        migrations.AddIndex(
            model_name='eventregistration',
            index=models.Index(fields=['event', 'status'], name='event_regis_event_i_6842e1_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventregistration',
            constraint=models.UniqueConstraint(fields=('event', 'member'), name='uniq_event_member'),
        ),
        migrations.AddIndex(
            model_name='eventtestimonial',
            index=models.Index(fields=['event', '-created_at'], name='event_testi_event_i_7a9c28_idx'),
        ),
        migrations.AddIndex(
            model_name='eventtestimonial',
            index=models.Index(fields=['is_published', '-created_at'], name='event_testi_is_publ_d62587_idx'),
        ),
    ]
